version: "3.9"
services:
  db:
    image: postgres:16
    ports: ["5432:5432"]
    environment:
      POSTGRES_USER: party
      POSTGRES_PASSWORD: party
      POSTGRES_DB: party
    volumes: [db:/var/lib/postgresql/data]
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
volumes:
  db:
