-- Add prompt fields to analysis_flows table
ALTER TABLE analysis_flows 
ADD COLUMN final_composed_prompt TEXT,
ADD COLUMN dall_e_prompt TEXT;

-- Add comments for documentation
COMMENT ON COLUMN analysis_flows.final_composed_prompt IS 'The complete prompt sent to GPT-4o including context and template';
COMMENT ON COLUMN analysis_flows.dall_e_prompt IS 'The DALL-E prompt generated by GPT-4o for image generation';
