-- Insert production data into local database
INSERT INTO "public"."prompt_definitions" ("id", "name", "type", "input_schema", "output_schema", "prompt_text", "return_schema", "model", "response_format", "max_tokens", "temperature", "active", "created_at", "updated_at", "sort_order") VALUES
('ca7ce6b4-8e9c-49ab-8a7e-2a5c980a13e3', 'image_analysis', 'image_analysis', '{"type": "object", "required": ["image"], "properties": {"image": {"type": "string"}}}', '{"type": "object", "required": ["response"], "properties": {"response": {"type": "string", "minLength": 10}, "artistic_notes": {"type": "string"}, "technical_notes": {"type": "string"}, "confidence_score": {"type": "number", "maximum": 1, "minimum": 0}, "identified_elements": {"type": "array", "items": {"type": "string"}}}}', 'You are an assistant that helps a child explain their drawing so it can be recreated as a professional-quality line drawing. Always follow these steps in order: Shape Inventory List all visible parts of the drawing as simple shapes (ovals, blobs, lines, circles). Include head, limbs, eyes, mouth, base, connectors, and decorations. Interpretation Options For each part, suggest 2–3 possible interpretations. Keep them playful, age-appropriate, and neutral. Organize by function (face feature, body part, accessory, decoration). Ambiguity Scan Assign confidence (High / Medium / Low). Mark all Low confidence parts for clarification.', '{"type": "object", "required": ["response"], "properties": {"response": {"type": "string", "minLength": 10}, "artistic_notes": {"type": "string"}, "technical_notes": {"type": "string"}, "confidence_score": {"type": "number", "maximum": 1, "minimum": 0}, "identified_elements": {"type": "array", "items": {"type": "string"}}}}', 'gpt-4o', 'json_object', NULL, NULL, true, '2025-09-05 19:00:12.701482+00', '2025-09-06 01:55:54.625321+00', 10),
('2aa869e5-ff94-4329-bb42-e85cb30fdfcf', 'image_generation', 'image_generation', '{"type": "object", "required": ["prompt"], "properties": {"prompt": {"type": "string", "minLength": 10}}}', '{"type": "object", "required": ["image_base64"], "properties": {"response": {"type": "string"}, "image_base64": {"type": "string"}}}', 'Final Line Drawing Spec Produce one complete, unambiguous description for an illustrator. Include: Head/face features (eyes, mouth, nose, teeth, horns, etc.) Limbs/appendages (arms, legs, wings, stalks, etc.) Base/connector/outline shape Accessories/decorations (patterns, clothing-like details) Notes on relative size, symmetry, and style consistency create a prompt for a polished line drawing description that stays true to the child''s intent which incorporates all of the answers and clarifications and analysis gathered.


From that prompt, generate an image which stays tru to the child''s drawing but incorporates all of the ideas into one coherent professional illustration.  Keep it fun, kid friendly and playful.', '{"type": "object", "required": ["image_base64"], "properties": {"image_base64": {"type": "string"}}}', 'dall-e-3', 'json_object', NULL, NULL, true, '2025-09-05 19:00:12.701482+00', '2025-09-06 02:08:45.883087+00', 40),
('8ec4530c-5f64-464d-9b85-b4a9992e90d6', 'questions_generation', 'questions_generation', '{"type": "object", "required": ["response"], "properties": {"response": {"type": "string"}}}', '{"type": "object", "required": ["questions"], "properties": {"response": {"type": "string"}, "questions": {"type": "array", "items": {"type": "object", "required": ["id", "text", "type", "options", "required"], "properties": {"id": {"type": "string"}, "text": {"type": "string", "minLength": 10}, "type": {"enum": ["multiple_choice"], "type": "string"}, "options": {"type": "array", "items": {"type": "string"}, "maxItems": 6, "minItems": 2}, "required": {"type": "boolean"}}}, "maxItems": 15, "minItems": 3}}}', 'Ask the Child For each ambiguous part: Ask 4 short, kid-friendly questions (no more than 12 words). Provide 2–3 answer choices with clear, simple labels. Example: "Is this part eyes, teeth, or decoration?" Wait for the answer before continuing. Refinement Update each clarified part with specific details about shape, placement, and proportion. Do not use animation or motion words.


keep it fun and adventurous.  Incorporate them in questions about the place and characters abilities.  Facilitate creativity.


', '{"type": "object", "required": ["questions"], "properties": {"questions": {"type": "array", "items": {"type": "object", "required": ["id", "text", "type", "options", "required"], "properties": {"id": {"type": "string"}, "text": {"type": "string"}, "type": {"enum": ["multiple_choice"], "type": "string"}, "options": {"type": "array", "items": {"type": "string"}}, "required": {"type": "boolean"}}}}}}', 'gpt-4o', 'json_object', NULL, NULL, true, '2025-09-05 19:00:12.701482+00', '2025-09-06 01:58:30.230635+00', 20);