name: Deploy Image Processor to Railway

on:
  push:
    branches: [main, mtd-feature/new-app]
    paths:
      - 'apps/image-processor/**'
      - '.github/workflows/deploy-image-processor.yml'
  workflow_dispatch:

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      should-deploy: ${{ steps.changes.outputs.image-processor }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Check for changes in image-processor
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            image-processor:
              - 'apps/image-processor/**'

  deploy:
    needs: check-changes
    if: needs.check-changes.outputs.should-deploy == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Deploy to Railway
        run: |
          echo "Deploying image-processor to Railway..."
          echo "Changes detected in apps/image-processor/"
          # Railway will automatically deploy via GitHub integration
          # This step is just for logging and can be extended with custom deployment logic
