name: Deploy Magic Marker

on:
  push:
    branches: [main, mtd-feature/new-app]
    paths:
      - 'apps/magic-marker/**'
      - 'apps/magic-marker/web/**'
      - 'apps/magic-marker/api/**'
      - '.github/workflows/deploy-magic-marker.yml'
  workflow_dispatch:

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      magic-marker: ${{ steps.changes.outputs.magic-marker }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            magic-marker:
              - 'apps/magic-marker/**'
              - '.github/workflows/deploy-magic-marker.yml'

  deploy:
    needs: changes
    if: ${{ needs.changes.outputs.magic-marker == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Magic Marker
        run: npx turbo build --filter=@tb2/magic-marker-web

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: apps/magic-marker/web
          vercel-args: '--prod'
